### ISSUE TITLE
__bridge error

### ISSUE THREAD

**Issue by Smy** [gohypergiant/BPXLUUIDHandler#2]
Hello

Thank you for your BPXLUUIDHandler.

I've found a little problem on a project without ARC, I need to remove __bridge to make it work on Xcode 4.2.

**Comment by rustle** [comment]
Fixed: https://github.com/blackpixel/BPXLUUIDHandler/commit/f434902e4023c97df5d6594f7b645a6fdd63b54c

Thanks for the heads up!

**Comment by Smy** [comment]
Thank you !!!
