### ISSUE TITLE
Problem with access group

### ISSUE THREAD

**Issue by ulfie22** [gohypergiant/BPXLUUIDHandler#4]
The function of the access group isn't covered in the documentation. My guess is that setting it will allow multiple apps with the same setting to access the same keychain entry and thereby learn of each other's presence on the device. However, if i set it:

[BPXLUUIDHandler setAccessGroup:@"some_name_of_mine"];

when the function

[BPXLUUIDHandler UUID]

gets called, this error results in the log:

BPXLUUIDHandler Keychain Save Error: -25243

Am I misunderstanding the function of setAccessGroup?

Thanks for publishing this - it is really helpful.

**Comment by ngreenstein** [comment]
The access group allows multiple apps from the same developer to share keychain entries. Check out the comment in `BPXLUUIDHandler.h` and [Apple's documentation](http://developer.apple.com/library/ios/#documentation/Security/Reference/keychainservices/Reference/reference.html#//apple_ref/c/func/SecItemAdd) for details.
