### ISSUE TITLE
doest the uuid changes when restoring to another device?

### ISSUE THREAD

**Issue by mltk96** [gohypergiant/BPXLUUIDHandler#9]
just want to know if the uuid you are returning is changes when restoring to a new device or not.
lets say i'm using device A ant it's uuid is 1, after backing up the device, and restoring it to a new device B, does the uuid you are returning will still be 1, or a new one?

tnx!

**Comment by ngreenstein** [comment]
The UUID does change when restoring to a new device:

> A full restore and setup as a new device ... wipes the keychain.
